; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = ${sysenv.HOME}/pio-build/uroflow

[env:esp32-s3-touch-lcd-7]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_8MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_build.f_cpu = 240000000L
upload_protocol = esptool
board_upload.before_reset = no_reset
board_upload.after_reset = no_reset
upload_flags = 
	--connect-attempts=20
	--no-stub
build_unflags = -DARDUINO_USB_MODE
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MODE=0
	-DGT911_DRIVER=1
	-DTFT_WIDTH=800
	-DTFT_HEIGHT=480
lib_deps = 
	h2zero/NimBLE-Arduino @ ^1.4.2
	milad-nikpendar/initGT911 @ ^1.0.0
	moononournation/GFX Library for Arduino@^1.4.9
